[package]
name = "langdb"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1.3"
thiserror = "1.0.49"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
anyhow = "1.0.75"
